### ISSUE TITLE
About the code release plan

### ISSUE THREAD

**Issue by hoi4d** [wyhuai/PhysHOI#1]
Hi,
 
Congratulations on a very interesting project! 

I wanna know when your code will be released, and I can't wait to try it out.

**Comment by wyhuai** [comment]
Thanks for your attention, the code will be released this month.

**Comment by VictoriYang** [comment]
Wonderful job! I'm wandering how to get the humanoid .xml. Thanks a lot.

**Comment by wyhuai** [comment]
> Hi,
> 
> Congratulations on a very interesting project!
> 
> I wanna know when your code will be released, and I can't wait to try it out.

Hi, the code is available now, hope you have fun.

**Comment by wyhuai** [comment]
> Wonderful job! I'm wandering how to get the humanoid .xml. Thanks a lot.

Hi, you can find the link at the bottom of README.md
