### ISSUE TITLE
pd control

### ISSUE THREAD

**Issue by hjlllll** [wyhuai/PhysHOI#4]
Hi,
thanks for your excellent work.
I am confused with one question, that is how does the "joint torques" calculated in paper? Because I saw the code use the gym.set_dof_position_target_tensor to control the human.

Thanks you again.

**Comment by wyhuai** [comment]
Hi, the policy outputs and sets the DOF position as the PD controller's target, using gym.set_dof_position_target_tensor. The joint torques are calculated by the PD controller, which is implemented by the system.

**Comment by hjlllll** [comment]
Thanks, I got it ,which means the pd controller is implemented by isaacgym.
Thanks a lot!
