### ISSUE TITLE
您好，想请教下数据集搭建这部分camera parameters estimation是怎么做的？

### ISSUE THREAD

**Issue by irenebae0329** [wyhuai/PhysHOI#5]
相机参数是单纯根据pose estimation模型得到的，还是有用别的方法，或者有自己作标注呢？感谢您的解答。

**Comment by wyhuai** [comment]
您好，相机参数是根据模型估计得到的，类似[motion-x](https://github.com/IDEA-Research/Motion-X)的方法。没有作人工标注

**Comment by irenebae0329** [comment]
> 您好，相机参数是根据模型估计得到的，类似[motion-x](https://github.com/IDEA-Research/Motion-X)的方法。没有作人工标注
好的，非常感谢您的回复。
