### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by Soumyabrata2003** [wyhuai/PhysHOI#8]
Hi, can you provide the evaluation code to replicate the results in the Tables (e.g. success rate, E_b-mpjpe etc)? It will be helpful.

**Comment by wyhuai** [comment]
> Hi, can you provide the evaluation code to replicate the results in the Tables (e.g. success rate, E_b-mpjpe etc)? It will be helpful.

Hi, thanks for your attention. We will release a new work that will contain the evaluation code you need, this take time and may come by the end of this month.
